# Generated by Django 5.2.1 on 2025-05-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'TODO'), ('2', 'IN_PROGRESS'), ('3', 'DONE')], default='1', max_length=10, verbose_name='Whats is your status?'),
        ),
    ]
